org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.5
fabric_version=0.116.17+1.21.1
mixinextras_version=0.3.5
sodium_version=mc1.21.1-0.8.13-fabric

mod_version=1.10.14
maven_group=de.selectiverender
archives_base_name=selective-render-mc1.21.1
