plugins {
    id 'fabric-loom' version '1.6.12'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base { archivesName = project.archives_base_name }

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://maven.terraformersmc.com/releases/' }
    maven { url = 'https://api.modrinth.com/maven' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation annotationProcessor("io.github.llamalad7:mixinextras-fabric:${project.mixinextras_version}")
    include "io.github.llamalad7:mixinextras-fabric:${project.mixinextras_version}"
    modCompileOnly "maven.modrinth:sodium:${project.sodium_version}"
    modCompileOnly "com.terraformersmc:modmenu:7.2.2"
    modLocalRuntime "maven.modrinth:sodium:${project.sodium_version}"
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

loom {
    splitEnvironmentSourceSets()
    runs {
        client {
            vmArg "-Dsodium.checks.issue2561=false"
        }
    }
    mods {
        selectiverender {
            sourceSet sourceSets.client
        }
    }
}

sourceSets.test {
    compileClasspath += sourceSets.client.output
    runtimeClasspath += sourceSets.client.output
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType(ProcessResources).configureEach {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand version: project.version }
}

tasks.named('processClientResources', ProcessResources) {
    from('docs/images/icon.png') { into 'assets/selectiverender' }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
    options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
